package anim

var foundingDocumentRunes = []rune(foundingDocumentText)

const foundingDocumentText = `Declaration of Independence. In Congress, July 4, 1776. The unanimous Declaration of the thirteen united States of America. We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness. Governments are instituted among Men, deriving their just powers from the consent of the governed. Whenever any Form of Government becomes destructive of these ends, it is the Right of the People to alter or to abolish it, and to institute new Government.

United States Constitution. We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defense, promote the general Welfare, and secure the Blessings of Liberty to ourselves and our Posterity, do ordain and establish this Constitution for the United States of America. Article I vests legislative power in Congress. Article II vests executive power in the President. Article III vests judicial power in one Supreme Court and such inferior Courts as Congress may establish. Article IV addresses the states. Article V provides amendment. Article VI establishes debts, supremacy, and oaths. Article VII provides ratification.

Bill of Rights. Amendment I. Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for redress of grievances. Amendment II. A well regulated Militia, being necessary to the security of a free State, the right of the people to keep and bear Arms shall not be infringed. Amendment III. No Soldier shall, in time of peace be quartered in any house, without consent of the Owner. Amendment IV. The right of the people to be secure against unreasonable searches and seizures shall not be violated. Amendment V. No person shall be held to answer for a capital, or otherwise infamous crime, unless on indictment of a Grand Jury, nor be deprived of life, liberty, or property, without due process of law. Amendment VI. In all criminal prosecutions, the accused shall enjoy the right to a speedy and public trial by an impartial jury. Amendment VII. In Suits at common law, the right of trial by jury shall be preserved. Amendment VIII. Excessive bail shall not be required, nor excessive fines imposed, nor cruel and unusual punishments inflicted. Amendment IX. The enumeration of certain rights shall not deny or disparage others retained by the people. Amendment X. Powers not delegated to the United States are reserved to the States respectively, or to the people.

Amendments XI through XXVII. The Eleventh limits federal judicial power over suits against states. The Twelfth revises presidential elections. The Thirteenth abolishes slavery. The Fourteenth guarantees citizenship, due process, equal protection, and apportionment rules. The Fifteenth protects voting rights regardless of race, color, or previous condition of servitude. The Sixteenth authorizes income taxes. The Seventeenth provides direct election of Senators. The Eighteenth prohibited intoxicating liquors. The Nineteenth protects voting rights regardless of sex. The Twentieth changes presidential and congressional terms. The Twenty-first repeals Prohibition. The Twenty-second limits presidential terms. The Twenty-third grants presidential electors to the District of Columbia. The Twenty-fourth bars poll taxes in federal elections. The Twenty-fifth addresses presidential succession and disability. The Twenty-sixth protects voting rights for citizens eighteen and older. The Twenty-seventh limits congressional pay changes until after an intervening election.

Emancipation Proclamation. By the President of the United States of America: A Proclamation. On the first day of January, in the year of our Lord one thousand eight hundred and sixty-three, all persons held as slaves within any State or designated part of a State, the people whereof shall then be in rebellion against the United States, shall be then, thenceforward, and forever free.

Gettysburg Address. Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal. We here highly resolve that these dead shall not have died in vain; that this nation, under God, shall have a new birth of freedom; and that government of the people, by the people, for the people, shall not perish from the earth.

Seneca Falls Declaration of Sentiments. We hold these truths to be self-evident: that all men and women are created equal; that they are endowed by their Creator with certain inalienable rights; that among these are life, liberty, and the pursuit of happiness. Whenever any form of government becomes destructive of these ends, it is the right of those who suffer from it to refuse allegiance to it, and to insist upon the institution of a new government.

Tear Down This Wall. General Secretary Gorbachev, if you seek peace, if you seek prosperity for the Soviet Union and Eastern Europe, if you seek liberalization, come here to this gate. Mr. Gorbachev, open this gate. Mr. Gorbachev, tear down this wall!

Letter from Birmingham Jail Excerpts. While confined here in the Birmingham City Jail, I came across your recent statement calling our present activities unwise and untimely. In any nonviolent campaign there are four basic steps: collection of the facts to determine whether injustices are alive; negotiation; self-purification; and direct action. Birmingham is probably the most thoroughly segregated city in the United States. Its ugly record of police brutality is known in every section of the country. Nonviolent direct action seeks to create such a crisis and establish such creative tension that a community that has constantly refused to negotiate is forced to confront the issue. We know through painful experience that freedom is never voluntarily given by the oppressor; it must be demanded by the oppressed. Justice too long delayed is justice denied. There comes a time when the cup of endurance runs over. Shallow understanding from people of good will is more frustrating than absolute misunderstanding from people of ill will. Let us all hope that the dark clouds of racial prejudice will soon pass away and the deep fog of misunderstanding will be lifted from our communities.

The Star-Spangled Banner. O say can you see, by the dawn's early light, what so proudly we hailed at the twilight's last gleaming, whose broad stripes and bright stars through the perilous fight, o'er the ramparts we watched, were so gallantly streaming? And the rocket's red glare, the bombs bursting in air, gave proof through the night that our flag was still there. O say does that star-spangled banner yet wave o'er the land of the free and the home of the brave?

`
